version: '3.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - nginx.html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  nginx-proxy-companon:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - "nginx-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - nginx.html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  ghost:
    image: ghost:1-alpine
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8080:2368
    volumes:
      - ./blog/data/ghost:/var/lib/ghost/content
    environment:
      - url=https://blog.aaronlenoir.com
      - VIRTUAL_HOST=blog.aaronlenoir.com
      - LETSENCRYPT_HOST=blog.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
  score:
    image: nginx:alpine
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./score/tablechamp-app:/usr/share/nginx/html:ro
    environment:
      - url=https://score.aaronlenoir.com
      - VIRTUAL_HOST=score.aaronlenoir.com
      - LETSENCRYPT_HOST=score.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
volumes:
  nginx.html:
