version: '3.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/dhparam:/etc/nginx/dhparam:rw
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - nginx.html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  nginx-proxy-companon:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - "nginx-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - nginx.html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  ghost:
    image: ghost:1-alpine
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8080:2368
    volumes:
      - ./blog/data/ghost:/var/lib/ghost/content
    environment:
      - url=https://blog-test.aaronlenoir.com
      - VIRTUAL_HOST=blog-test.aaronlenoir.com
      - LETSENCRYPT_HOST=blog-test.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
  flightschool:
    image: ghost:1-alpine
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8090:2368
    volumes:
      - ./flightschool/data/ghost:/var/lib/ghost/content
    environment:
      - url=https://test-flightschool.aaronlenoir.com
      - VIRTUAL_HOST=test-flightschool.aaronlenoir.com
      - LETSENCRYPT_HOST=test-flightschool.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
  kicker:
    image: kicker
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8100:80
    volumes:
      - ./kicker/Configuration:/app/Configuration
    environment:
      - url=https://kicker.aaronlenoir.com
      - VIRTUAL_HOST=kicker.aaronlenoir.com
      - LETSENCRYPT_HOST=kicker.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
  tracks:
    image: tracks
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8110:80
    environment:
      - url=https://tracks.aaronlenoir.com
      - VIRTUAL_HOST=tracks.aaronlenoir.com
      - LETSENCRYPT_HOST=tracks.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
  ghost2:
    image: ghost:2-alpine
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8120:2368
    volumes:
      - ./blog2/data/ghost:/var/lib/ghost/content
    environment:
      - url=https://blog.aaronlenoir.com
      - VIRTUAL_HOST=blog.aaronlenoir.com
      - LETSENCRYPT_HOST=blog.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
  flightschool2:
    image: ghost:2-alpine
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8130:2368
    volumes:
      - ./flightschool2/data/ghost:/var/lib/ghost/content
    environment:
      - url=https://flightschool.aaronlenoir.com
      - VIRTUAL_HOST=flightschool.aaronlenoir.com
      - LETSENCRYPT_HOST=flightschool.aaronlenoir.com
      - LETSENCRYPT_EMAIL=info@aaronlenoir.com
volumes:
  nginx.html:
